### ISSUE TITLE
Why is the LivingDeathEvent processing player deaths on the lowest priority?

### ISSUE THREAD

**Issue by HoldYourWaffle** [iChun/Death-Counter#1]
The LivingDeathEvent processing player deaths has the lowest priority, is there a reason for that?

Asking because I'm making a server-side addon mod that puts the leaderboard in chat everytime someone dies. With the lowest priority however, I can't execute my event handler *after* your mod has processed the death fully.

**Comment by iChun** [comment]
Because I'm allowing other mods to cancel the event first so that I won't
get the event if the event is cancelled. Death counter just keeps tracks of
deaths. It doesn't do anything else.

**Comment by HoldYourWaffle** [comment]
I moved it up to low would that be okay? This way it still allows for other mods to hook into DC's behavior.

**Comment by iChun** [comment]
The priority system just defines the priority. If more than one mod uses
lowest they'd both still be called when the event fires. I'm having trouble
figuring out what your issue with DC is, actually.

On 23 Dec 2017 11:15 PM, "Ravi van Rooijen" <notifications@github.com>
wrote:

I moved it up to low would that be okay? This way it still allows for other
mods to hook into DC's behavior.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/iChun/Death-Counter/issues/1#issuecomment-353724351>,
or mute the thread

**Comment by HoldYourWaffle** [comment]
My problem is that I can't hook into DC's behavior at the LivingDeathEvent *after* it has processed the death.

My use case:
I want to execute the `dc leaderboard all` command everytime someone dies. If my event handler has a higher/the same priority as yours it'll be processed before DC has increased it's death count, thus displaying a wrong leaderboard. To fix this your event handler must have a higher priority than mine.

**Comment by iChun** [comment]
Ahhh okay gotcha gotcha. Fair enough.

On 25 Dec 2017 3:06 AM, "Ravi van Rooijen" <notifications@github.com> wrote:

My problem is that I can't hook into DC's behavior at the LivingDeathEvent
*after* it has processed the death.

My use case:
I want to execute the dc leaderboard all command everytime someone dies. If
my event handler has a higher/the same priority as yours it'll be processed
before DC has increased it's death count, thus displaying a wrong
leaderboard. To fix this your event handler must have a higher priority
than mine.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/iChun/Death-Counter/issues/1#issuecomment-353799097>,
or mute the thread

**Comment by HoldYourWaffle** [comment]
So what do you think? Moving your priority up by one or do you know of a better way to solve this. 
(I understand this is kinof "dirty" because as you said, DC doesn't do anything by itself so it should have a low priority.)

**Comment by iChun** [comment]
What is the mod id of the mod you plan to do this with?

**Comment by HoldYourWaffle** [comment]
It's 'adl'

I published the mod here: [AutoDeathLeaderboard](https://github.com/HoldYourWaffle/AutoDeathLeaderboard)

**Comment by iChun** [comment]
One thing for a potential workaround for the moment is to listen to the
death event and on the next tick just call the command as well. Because
your modid is before 'd', your mod is processed earlier than DC sadly.

On 27 Dec 2017 10:02 PM, "Ravi van Rooijen" <notifications@github.com>
wrote:

It's 'adl'

I published the mod here: AutoDeathLeaderboard
<https://github.com/HoldYourWaffle/AutoDeathLeaderboard>

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/iChun/Death-Counter/issues/1#issuecomment-354118219>,
or mute the thread

**Comment by HoldYourWaffle** [comment]
I could also create a PR that adds ADL's functionality to your mod (with a configuration option of course), that seems like a more clean and simpeler solution.

**Comment by HoldYourWaffle** [comment]
I have no idea why that commit references this issue, it should be #3 🤔
