### ISSUE TITLE
The new 1.3.0 Update breaks Vanilla support

### ISSUE THREAD

**Issue by Pokihead** [iChun/Death-Counter#11]
I updated to the new 1.3.0 Version for 1.19.3 support.
If i now broadcast the leaderboard Vanilla clients or clients without the mod only see:
_commands.deathcounter,leaderboard.broadcasted
commands.deathcounter.leaderboard.copy_
and so on
Here an picture:
![grafik](https://user-images.githubusercontent.com/37344330/220484879-3c9776b2-3a8a-4b4f-8bd4-8e778ffc704a.png)
Using forge-1.19.3-44.1.17 
I'm sure that in 1.19.2 and mod version 1.2.1 that worked.

**Comment by iChun** [comment]
Apologies for the late response, you might have figured it out by now: 

This change is in relation to what MC has done internally for translatable texts, to allow players running different locales to have accurately translated information. Because of this, clients without this mod installed will not have the accurate translation keys and will output those keys into chat instead of what you expect, the translated message.

There's not much I can do about this if I want to continue having localisations in my mods. I'd also like to strongly discourage you from allowing vanilla clients to connect to modded servers, I'm sure you have your reasons but a lot of things can go wrong due to the mismatched environments.
